# Configuraci칩n para el script de reanudaci칩n autom치tica de misiones

credentials:
  user: 'ander.sein@servexternos.repsol.com'
  key: 'hPAPq3u1.BMjE7X8d1NrmKdp6OxhpD/Y3LeUjLNq4yGMssSR0NU8IpTG/'

robot_info:
  id: "67adc0f808e884ffb30b63e9"

api_endpoints:
  # Usamos la URL HTTP para todas las operaciones
  graphql_url: "https://api.graphql.energy-robotics.com/graphql"
  login_url: "https://login.energy-robotics.com/api/loginApi"

settings:
  # Cada cu치ntos segundos comprobar el estado del robot.
  # Se recomienda no poner un valor muy bajo para no sobrecargar la API.
  check_interval_seconds: 10 # 1 minuto

  # Tiempo de espera en segundos entre los comandos de la secuencia (asleep -> awake -> resume)
  action_delay_seconds: 10