# Configuración para el script de reanudación automática de misiones
credentials:
  user: 'ander.sein@servexternos.repsol.com'
  key: 'hPAPq3u1.BMjE7X8d1NrmKdp6OxhpD/Y3LeUjLNq4yGMssSR0NU8IpTG/'

robot_info:
  id: "67adc0f808e884ffb30b63e9"

api_endpoints:
  graphql_url: "https://api.graphql.energy-robotics.com/graphql"
  login_url: "https://login.energy-robotics.com/api/loginApi"

settings:
  check_interval_seconds: 10
  action_delay_seconds: 10

# Define las condiciones que deben cumplirse para iniciar una recuperación
recovery_triggers:
  # El último evento debe haber ocurrido en los últimos X segundos para ser considerado relevante
  max_event_age_seconds: 30 # 30 segundos

  # Lista de mensajes de evento que son considerados "seguros" para una recuperación automática
  event_messages:
    - "notification.behaviorNavigationFailed" 
    - "notification.behaviorDockingMaximumRetriesExceeded"
    - "notification.behaviorprincipaldrivernotsupervising"
    - "notification.behaviorwirelesschargerconnectionfailed"